### ISSUE TITLE
Host on Edge extension as well as Chrome extension

### ISSUE THREAD

**Issue by samspade** [M1ck0/adskipper-extension#1]
Host on Edge Store

I can't access the Chrome extension store, but I can get access to the Edge extensions. Is it possible to make it available in the Edge one as well? 

It would be lovely. Thanks

**Comment by M1ck0** [comment]
@samspade 

Well, I didn't host it on Edge since I thought that Edge users can install them from Chrome store.

I will definitively add it on Edge store as well. That might take a day or two, but it will be up for sure. I'll write here when I do that. 

Thanks for the report

**Comment by M1ck0** [comment]
https://microsoftedge.microsoft.com/addons/detail/ad-skipper/acibmijbokdhjlmcnjpdopnkifmchaom
