### ISSUE TITLE
Detected by youtube

### ISSUE THREAD

**Issue by unicorntank** [M1ck0/adskipper-extension#11]
![螢幕擷取畫面 2024-04-19 124333](https://github.com/M1ck0/adskipper-extension/assets/167530725/7ec00b8d-a161-4535-9c4b-3ba1ab065e75)
![螢幕擷取畫面 2024-04-19 124649](https://github.com/M1ck0/adskipper-extension/assets/167530725/21f46ef4-8cdb-4db6-9cf0-15017a4d6d1b)
![螢幕擷取畫面 2024-04-19 124835](https://github.com/M1ck0/adskipper-extension/assets/167530725/c5f803cd-d96e-413a-836c-8ce57865db42)
![螢幕擷取畫面 2024-04-19 124903](https://github.com/M1ck0/adskipper-extension/assets/167530725/42827d17-d9de-4a3b-99d3-9266ecb8961b)

Starting yesterday, YouTube detected my adskipper, and then today I updated my extension to latest version but nothing changed. I also screenshot the errors shown in Developer Mode, not sure it will help or not.

**Comment by M1ck0** [comment]
Thanks a lot for the report, it is really helpful.

You don't have any other adblocking extension installed?

**Comment by unicorntank** [comment]
Yes I do have other adblock extension installed, but I disabled all adblock except adskipper when using youtube.

**Comment by M1ck0** [comment]
Update to the 2.8.8 and see if the issue persists

**Comment by unicorntank** [comment]
updated to 2.8.8 version. But the issue persists. I had to reload the webpage to play the video.

**Comment by M1ck0** [comment]
I see. Could you do this
- Remove AdSkipper fully
- Go to youtube and pay few videos to see if the issue still persists

If it does, then some other extension is causing the issue. I've seen some cases on reddit here youtube detected that adblocker was installed even tho it was disabled.

**Comment by unicorntank** [comment]
I removed all Adblock on Chrome, but the issue persists. However, I tried the same thing on Microsoft Edge, and Adskipper worked. I'm not sure if it is related to the Eset anti-virus extension on Chrome because I didn't install this extension on Edge. Thank you!

**Comment by M1ck0** [comment]
It could be related to that extension. I will close this issue for now but please feel free to open another issue if you encounter any problems.
Thank you so much for helping
