### ISSUE TITLE
Adskipper does not skip surveys.

### ISSUE THREAD

**Issue by StickyChannel92** [M1ck0/adskipper-extension#12]
I just experience a time where adskipper does not skip surveys. You have to wait 5 seconds for it to go away.

Maybe this helps?
TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite. at stopYoutubeAd (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:22:27) at chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:84:15

**Comment by M1ck0** [comment]
@StickyChannel92 Thanks for reporting this. 

I don't get surveys so it is harder to debug, but I'll release an update in the next few days that will hopefully fix this so make sure you keep an eye out for that update.

I will close this now, but please open new issue if same problem persists after the upcoming updated
