### ISSUE TITLE
Youtube detects Adskipper

### ISSUE THREAD

**Issue by TheDefaultCube** [M1ck0/adskipper-extension#13]
Hello! Extension has been working absolutely amazingly until now, but it seems that as of May 30 something has changed in the API - Youtube now detects the adskipper and gives you the adblock warning. 

Unsure if this is something that can be fixed at all, but I'd thought I'd let you know here at least. 

Thanks for all of your work thus far. It's been very appreciated 👍

**Comment by M1ck0** [comment]
Hey, thanks for the report. What browser are you using?

**Comment by AndreMantas** [comment]
Same here. 
Chrome 
Version 125.0.6422.113

I also got this error on the extension's options page
> TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite. at stopYoutubeAd (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:22:27) at chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:84:15

**Comment by Sortexx** [comment]
Same here

**Comment by M1ck0** [comment]
@Sortexx @AndreMantas 

Version 3 is live on Firefox and pending review on Chrome. Please keep an eye out for the update and do report your findings. Thanks a lot and sorry for incovenience

**Comment by TheDefaultCube** [comment]
> Hey, thanks for the report. What browser are you using?

I'm using the Arc Browser version 1.4.4.3 (I believe it's pretty much a reskinned chromium)

**Comment by M1ck0** [comment]
@TheDefaultCube I am also on Arc and yeah, it is reskinned chromium. Version 3 is still in review on Chrome Store (damn they are slow).

**Comment by jkdrz** [comment]
I'm on Firefox 126 with version 3 of the extension and Youtube keeps feeding me the Adblocker screen. Yesterday, refreshing the page let videos play but today every video gets hit with the detector.

edit: videos seem to be really hit and miss now with getting hit by the adblock detection, sometimes it works, sometimes it doesn't.

**Comment by KcDaRookie** [comment]
Am also on Firefox with V3 and especially pre-vid ads will get detected when skipped. I have yet to face a detection when skipping ads when the video is already playing.

**Comment by M1ck0** [comment]
Version 3.2 is up and running today. Make sure you update it and everything should work. I will close this but if problem persists, please open new issue. 

Thanks.
