### ISSUE TITLE
Youtube Detecting the Extension

### ISSUE THREAD

**Issue by JonathanDHall** [M1ck0/adskipper-extension#14]
Youtube Detecting the extension as of today. Videos no longer play due to Youtube detecting an Ad Blocker. No other Ad Blockers installed.
On Chrome, and no errors on the Options Page.

**Comment by M1ck0** [comment]
Version 3 is submitted and should be live soon on Chrome. Please keep an eye out for the update and report back if issue persists. Thank you

**Comment by janmichael88** [comment]
Same issue here. I have to hit refresh like once or twice for it to go away. 

Will the new version auto update?

**Comment by M1ck0** [comment]
@janmichael88 I am not sure about autoupdate. Depends on your system, but please check in a few hours for it, as it is still pending for review (google is kinda slow)

**Comment by StickyChannel92** [comment]
Same issue here as well! So far, the update hasn't arrived for me yet.

EDIT: Just got the update and it works fine now.

**Comment by M1ck0** [comment]
Version 3.2 is up and running today. Make sure you update it and everything should work. I will close this but if problem persists, please open new issue. 

Thanks.
