### ISSUE TITLE
Making Youtube Slower and sometimes detects ad skipping

### ISSUE THREAD

**Issue by janmichael88** [M1ck0/adskipper-extension#15]
I'm noticing that when ad skipper is on it slows down the youtube webpage for me. It takes few seconds for the page to load. Sometimes video's a take a few seconds to load.

Also sometimes it still detects ad skipper. 

I'm on chrome

**Comment by maverick111x** [comment]
I noticed the same behavior on both chrome and edge.

**Comment by janmichael88** [comment]
Edit: Seems to be ok now. I tried removing the extension and re-installing it. I'll reply back if the issue persists!

**Comment by JonathanDHall** [comment]
Noticed the same.

**Comment by StickyChannel92** [comment]
Just got detected by YouTube now.

**Comment by StickyChannel92** [comment]
Just for reference, it has blocked playback on Donut Media and Real Mechanic Stuff.
Sample video: https://www.youtube.com/watch?v=DsmuwU92r_s

**Comment by erikbelusic** [comment]
mine is not working again
```
TypeError: Failed to set the 'currentTime' property on 'HTMLMediaElement': The provided double value is non-finite. at stopYoutubeAd (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:144:25) at chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:192:13 at Array.forEach () at MutationObserver.observerCallback (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:188:15)
```

**Comment by M1ck0** [comment]
Version 3.2 is up and running today. Make sure you update it and everything should work. I will close this but if problem persists, please open new issue. 

Thanks.
