### ISSUE TITLE
YouTube Playback Problems

### ISSUE THREAD

**Issue by livejamie** [M1ck0/adskipper-extension#16]
I noticed that videos within Reddit embeds have audio but no video and have narrowed it down to the AdSkipper extension.

It's happening for me in both Chrome and Edge. I am on version 3.2.

Example video: https://old.reddit.com/r/ROGAlly/comments/1dfwtgj/gamers_nexus_asus_sit_down/

(You need [Reddit Enhancement Suite](https://redditenhancementsuite.com/) installed to have the embeds show inline)

Another odd thing is when I click through the video it appears to play twice, with one feed more delayed, but when I pause the video it continues playing.

![chrome_oIfC85EZh5](https://github.com/M1ck0/adskipper-extension/assets/49513/42d127d6-6308-4de7-bc83-01c37e982324)

**Comment by acyrul** [comment]
Also, if the owner of a video disabled "Playback on other pages", you can't load the video, cause apparently skipping the ads at the beginning is treated as if you're watching an embedded video.
You CAN click "View on Youtube", but that just opens a new tab, skips the ads and views the same thing again.

**Comment by briarpatchdragon** [comment]
I am having the same problem, of blacked out embedded videos, etc., when Ad Skipper 3.2 is enabled.  The embed code was obtained simply by clicking the YouTube Share button.  It is a recent problem affecting existing sites.  I have not updated my Chrome Web browser, so I think that something changed on YouTube's side.

**Comment by M1ck0** [comment]
I am aware of the issue and it is fixed in version 3.5. It is live on Firefox and will be soon live on Chrome (when they review it) so make sure you update it as soon as possible.

I will close this for now, but feel free to open new issue if it happens again. Thanks
