### ISSUE TITLE
Only Members videos get blocked with 3.2 version.

### ISSUE THREAD

**Issue by AdsonEsteves** [M1ck0/adskipper-extension#17]
One of the channels I'm a member of, released a new video only for members.
However I got stopped from watching it with the message saying I'm not a member.
Once I deactivated the Adskipper I was able to watch it.

No errors are shown in the options log.

Version 3.2

**Comment by M1ck0** [comment]
I am aware of the issue and it is fixed in version 3.5. It is live on Firefox and will be soon live on Chrome (when they review it) so make sure you update it as soon as possible.

I will close this for now, but feel free to open new issue if it happens again. Thanks
