### ISSUE TITLE
Video becomes its own embed

### ISSUE THREAD

**Issue by StickyChannel92** [M1ck0/adskipper-extension#18]
![image](https://github.com/M1ck0/adskipper-extension/assets/48563620/7685cc20-89f9-43fd-aaf8-29756e749c91)
Video player becomes its own embed and sometimes plays the video underneath as well as the embed too, with 2 players playing at the same time. I have to pause the "undervideo" by clicking on the page and pressing the spacebar, then it would make the video more tolerable. Unfortunately, this does not mark the video as watched and my recommendations on the home page get clogged up with videos I have already watched (that I watched thru the bugged embed). Is this normal behavior for Ad Skipper?

RECORDED ERROR:
`ReferenceError: removePageAds is not defined at stopYoutubeAd (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:205:5) at chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:331:13 at Array.forEach () at MutationObserver.observerCallback (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:327:15)`

**Comment by thebebee** [comment]
also causes videos that are age restricted to be unplayable because they are embedded

**Comment by M1ck0** [comment]
I am aware of the issue and it is fixed in version 3.5. It is live on Firefox and will be soon live on Chrome (when they review it) so make sure you update it as soon as possible.

I will close this for now, but feel free to open new issue if it happens again. Thanks
