### ISSUE TITLE
Video losing player controls

### ISSUE THREAD

**Issue by imteekay** [M1ck0/adskipper-extension#19]
Thanks for the extension, it's working greatly for most of the cases 🎉 

I noticed that after using this AdSkipper, I lost control over the video player controls. It's not focused on the controls anymore so clicking `space` (to play/pause) and the `arrows` (forward, backward, volume up/down) doesn't work.

It seems the implementation adds an iframe to the page on top of the actual video player (z-index?). Is it possible to keep the video player controls from the iframe focused rather than the actual youtube video player? That way it would keep the same behavior as youtube, meaning, if you click any part of the page, it gives control back to the video player control.

**Comment by sgaleraalq** [comment]
It also removes the autoplay button, and videos do not play continuously.

**Comment by M1ck0** [comment]
I am aware of the issue and it is fixed in version 3.5. It is live on Firefox and will be soon live on Chrome (when they review it) so make sure you update it as soon as possible.

I will close this for now, but feel free to open new issue if it happens again. Thanks
