### ISSUE TITLE
New adskipper for android mobile

### ISSUE THREAD

**Issue by ghost** [M1ck0/adskipper-extension#24]
Can u make an app that does this but for all apps and u just have to turn it on and it automatically does the skipping?

**Comment by ghost** [comment]
Just don't make it a literal app on Google Play or u will get fined or something like that. Make ur own website and put it on thier.

**Comment by M1ck0** [comment]
That one is a big harder to make but I am doing my best in researching all the possibilities.

Also, for questions open the new Discussion, not an issue as it keeps everything nice and easy to manage.
