### ISSUE TITLE
Adskipper detected (August 2024)

### ISSUE THREAD

**Issue by StickyChannel92** [M1ck0/adskipper-extension#25]
![image](https://github.com/user-attachments/assets/6c5b7550-0e7a-4bc8-b4f0-88d48eb80e8e)

ERRORS: ReferenceError: removePageAds is not defined at stopYoutubeAd (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:205:5) at chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:331:13 at Array.forEach () at MutationObserver.observerCallback (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:327:15)

PROBLEMATIC EXAMPLE VIDEO: https://www.youtube.com/watch?v=lxJsesuG4IQ

POSSIBLE SOLUTION: Revert back to replacing the base player with the embed from previous version.

**Comment by TheBSODAndWSODFan** [comment]
are you using opera browser?
maybe disable the built-in adblock

i know its opera because i saw the upload icon is different (up arrow icon instead of camera icon)

or, maybe you're in ssap ads experiment which inject ads to the stream (server side ads)

**Comment by StickyChannel92** [comment]
> are you using opera browser? maybe disable the built-in adblock

I'm using Opera GX, but the built-in adblocker is turned off (AdBlock Plus clone, I assume?). I instead have uBlock Origin, but had it disabled for the time.

> or, maybe you're in ssap ads experiment which inject ads to the stream (server side ads)

I don't recall ever joining the experiments, as the ads do indeed skip before showing this popup message.
For context, jDownloader2 can download any video without the ads injected into the file.

**Comment by M1ck0** [comment]
I am aware of the issue and it is fixed in version 3.5. It is live on Firefox and will be soon live on Chrome (when they review it) so make sure you update it as soon as possible.

I will close this for now, but feel free to open new issue if it happens again. Thanks

**Comment by imteekay** [comment]
@M1ck0 I'm currently running into this problem too. The version of my extension is 3.7.

**Comment by Xmetalfanx** [comment]
currently seeing the same issue (note: ublock origin is installed but disabled on LibreWolf here ... a Firefox fork by the way) . 

I am on version 3.9 of the extension.

I may remove UBO just as a test to see if even if its installed but disabled on Youtube if that is interfering
