### ISSUE TITLE
Add support for YouTube Shorts blocking on mobile home page

### ISSUE THREAD

**Issue by outsparkled** [M1ck0/adskipper-extension#29]
[The code responsible for blocking shorts on the home page](https://github.com/M1ck0/adskipper-extension/blob/41b997afeb28ae8adf7a8dd1d7adf1d99266d766/scripts/youtube.js#L45) currently uses the `is-shorts` attribute on the `ytd-rich-shelf-renderer` element to detect the Shorts section. This however only works on desktop, since YouTube on mobile (m.youtube.com) does not use this attribute.

I did some poking around on the mobile home page and found that the `grid-shelf-view-model` on the mobile website seems to be used exclusively for the Shorts section. This could be used to block shorts on mobile as well by removing all `grid-shelf-view-model` elements.

If you are interested, I would be happy to make a pull request with such a change.

**Comment by M1ck0** [comment]
Yeah, this would be neat. If you don't have time, tell me and I'll make it.

Thanks a lot fore research <3

@outsparkled
