### ISSUE TITLE
On Firefox skips subsequent videos after adds

### ISSUE THREAD

**Issue by KcDaRookie** [M1ck0/adskipper-extension#3]
If a new video starts after one has finished it is skipped with the adds

**Comment by M1ck0** [comment]
Thanks for the report. I am working on this issue. Will get back to you once I'm done.

**Comment by hero2zer0** [comment]
Just to add that this happens even on "new" videos, ie just clicked on a video and it just skips to it's end.

**Comment by M1ck0** [comment]
@KcDaRookie @hero2zer0 
Version 2.8.3 should fix the issue. It is live for Firefox and will be live for Chromium based browser tomorrow.

I will close this for now. Feel free to reopen it if the issue persists.

**Comment by KcDaRookie** [comment]
Seems to be working like a charm again, thanks a lot mate
