### ISSUE TITLE
Ad skipper does not skip full-screen sections of certain ads

### ISSUE THREAD

**Issue by StickyChannel92** [M1ck0/adskipper-extension#4]
When YouTube plays certain ads, it sometimes shows up a full-screen pop-up that has a button to the official website of the ad; it goes away after a few seconds. Ad skipper does not skip that apparently. And when the pop-up disappears or is skipped, the video you want to watch instantly ends.
![image](https://github.com/M1ck0/adskipper-extension/assets/48563620/f96b74ba-3f3f-4c69-a60b-3bf10873a0e4)

**Comment by M1ck0** [comment]
Thanks a lot for report, it is quite helpful.

Update should be released soon.

**Comment by M1ck0** [comment]
@StickyChannel92 
Version 2.8.3 should fix the issue. It is live for Firefox and will be live for Chrome (Opera) tomorrow.

I will close this for now. Feel free to reopen it if the issue persists.

**Comment by StickyChannel92** [comment]
This issue is still happening, and as such the second ad plays like normal instead of skipping it, albeit that I can skip it manually without waiting 5 seconds.
