### ISSUE TITLE
Does not skip midroll ads

### ISSUE THREAD

**Issue by Knniff** [M1ck0/adskipper-extension#5]
Firefox Version 122.0 (64-bit)
Adskipper Version 2.8
Used together with SponsorBlock 5.5.3 (dont know if they interact)

**Comment by M1ck0** [comment]
Thanks for reporting. I am aware of the issue and are working on it. Stay tuned for the update

**Comment by M1ck0** [comment]
@Knniff 
Version 2.8.3 should fix the issue

I will close this for now. Feel free to reopen it if the issue persists.

**Comment by Knniff** [comment]
Seems like its working correctly, had no more problems

thanks for your work
