### ISSUE TITLE
[Feature] In-feed ad blocking

### ISSUE THREAD

**Issue by Crunchbits** [M1ck0/adskipper-extension#6]
One thing I'd like to see would be in-feed ad blocking. For ad banners & promoted/ad videos that show up in YouTube search results and the YouTube Home page. I think this would be a great addition.

**Comment by M1ck0** [comment]
I can make that option and users can toggle it.

Reason why I didn't make it initially is because I didn't want to block anything that's not intrusive. I'll get back to you once it's done.

**Comment by M1ck0** [comment]
I gave up on this because after some research, this could mean that adskipper will be detectable easily, which is not my goal.
