### ISSUE TITLE
Second ad plays after first normally, but can be skipped without timer

### ISSUE THREAD

**Issue by StickyChannel92** [M1ck0/adskipper-extension#7]
After fixing the issue I mentioned #issue-2103567400, the first ad is skipped but the second one plays normally, and sometimes, the full-screen banner still shows up.

Unfortunately, I don't know how to open an issue back up, since I don't see an option in my issue to do so, so I opened a new one just in case.

**Comment by M1ck0** [comment]
I just added version 2.8.4. Make sure you have it installed and come back to share if it works. I won't be closing this issue until you come.

@StickyChannel92

**Comment by StickyChannel92** [comment]
It's still happening. Should I submit some sort of log file? If so, where can I find them?
Forgot to mention that I'm on Opera 107.0.5045.15.

**Comment by M1ck0** [comment]
@StickyChannel92 

Go into Options and you'll see a toggle that says "Show Errors". Turn it on, click Save and close that page. After the ad skipping fails, open Options page again and you'll see the error. Copy and paste it here.

<img width="1404" alt="Screenshot 2024-02-12 at 12 14 51" src="https://github.com/M1ck0/adskipper-extension/assets/19279947/fe3ac203-afb3-4b54-9f1b-418ce58ae758">

**Comment by StickyChannel92** [comment]
So far, it's not giving me any errors for the past day, but here is a clip of the action happening when AdSkipper is on.
https://github.com/M1ck0/adskipper-extension/assets/48563620/b1229a5f-7b3f-4de2-9d0a-459cd280d138

**Comment by StickyChannel92** [comment]
Also does not skip ads that say "Video plays soon" to make you wait.

**Comment by M1ck0** [comment]
Make sure you update to 2.8.5 which is release today on Firefox and uploaded for Chrome (should be available in next 24hrs)

I'll close this for now, but make sure to open a new issue if you encounter any problems. Thank you
