### ISSUE TITLE
Adskipper doesn't work

### ISSUE THREAD

**Issue by BinGlazzy** [M1ck0/adskipper-extension#8]
That's what the error code is:

TypeError: Cannot read properties of undefined (reading 'querySelector') at clickSkipButton (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:4:32) at stopYoutubeAd (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:23:7) at MutationObserver. (chrome-extension://dinhbmppbaekibhlomcimjbhdhacoael/scripts/youtube.js:74:13)

**Comment by M1ck0** [comment]
Make sure you are on 2.8.4 which was release today. It fixes this issue. Thanks for reporting. I will close it now, so feel free to open another one if it still happens.
