### ISSUE TITLE
YouTube detecting it?

### ISSUE THREAD

**Issue by Riekopo** [M1ck0/adskipper-extension#9]
![Screenshot_29-2-2024_3955_www youtube com](https://github.com/M1ck0/adskipper-extension/assets/98928426/954eae7e-0835-4b47-819f-507d54c44503)

Is YouTube detecting the extension now?

**Comment by Batuhan445** [comment]
i got it errors now

**Comment by M1ck0** [comment]
Version 2.8.5 is being uploaded for Chrome and is already active for Firefox so make sure you update it.

I'll close this issue for now, but feel free to open a new one after checking. Thank you
